# Generated by Django 2.2.5 on 2022-04-19 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 1, 42, 34, 680496), verbose_name='date published'),
        ),
    ]
