# Generated by Django 2.2.5 on 2022-04-19 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220420_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='basic_skills',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_of_study',
        ),
        migrations.AlterField(
            model_name='service',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 1, 45, 49, 78126), verbose_name='date published'),
        ),
    ]
