# Generated by Django 2.2.5 on 2022-04-19 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220420_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 1, 59, 14, 844405), verbose_name='date published'),
        ),
    ]
