# Generated by Django 2.2.5 on 2022-04-19 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220420_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone_no',
            field=models.CharField(default=9359580847, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 1, 59, 19, 259939), verbose_name='date published'),
        ),
    ]
